// HTTP STATUS CODES
const HTTP_STATUS_OK = 200;
const HTTP_STATUS_UNAUTHORIZED = 401;
const HTTP_NO_CONTENT = 204; 
// ENDPOINTS

// USER
const GET_USER_ENDPOINT_URL  = "/user/get";
const EDIT_USER_ENDPOINT_URL = "/user/edit"
//AUTH 
const LOGIN_ENDPOINT_URL  = "/auth/login";
const REGISTER_ENDPOINT_URL  = "/auth/register";
const PING_AUTH_ENDPOINT_URL  = "/auth/pingauth";

// Collection
const COLLECTION_LIST_ENDPOINT_URL = "/collection/list";
const COLLECTION_CREATE_ENDPOINT_URL = "/collection/create";
const COLLECTION_EDIT_ENDPOINT_URL = "/collection/edit";
const COLLECTION_DELETE_ENDPOINT_URL = "/collection/delete";

// Image
const IMAGE_GET_ENDPOINT_URL = "/image/get";
const IMAGE_GET_PAGED_ENDPOINT_URL = "/image/get/paged";
const IMAGE_GET_ALL_ENDPOINT_URL = "/image/get/all";
const IMAGE_EDIT_ENDPOINT_URL = "/image/edit";
const IMAGE_DELETE_ENDPOINT_URL = "/image/delete";

// API key
const APIKEY_GET_ENDPOINT_URL = "/apikey/get";
const APIKEY_LIST_ENDPOINT_URL = "/apikey/list";
const APIKEY_ADD_ENDPOINT_URL = "/apikey/add";
const APIKEY_EDIT_ENDPOINT_URL = "/apikey/edit";
const APIKEY_DELETE_ENDPOINT_URL = "/apikey/delete"
// UPLOAD
const UPLOAD_ENDPOINT_URL = "/upload"
    
// Metrics
const TOTAL_RESOURCE_USAGE_METRICS_ENDPOINT = "/metrics/get"
const DAILY_RESOURCE_USAGE_METRICS_ENDPOINT = "/metrics/daily/get"
// Logs 
const GET_API_KEY_LOGS_ENDPOINT = "/logs/apikey/get"
// NOTIFICATIONS TYPES
const NOTIFICATION_TYPE_SUCCESS = "success"
const NOTIFICATION_TYPE_ERROR = "error"
export {
    HTTP_STATUS_OK,
    HTTP_STATUS_UNAUTHORIZED,
    HTTP_NO_CONTENT,
    GET_USER_ENDPOINT_URL,
    LOGIN_ENDPOINT_URL,
    EDIT_USER_ENDPOINT_URL,
    REGISTER_ENDPOINT_URL,
    PING_AUTH_ENDPOINT_URL,
    NOTIFICATION_TYPE_SUCCESS,
    NOTIFICATION_TYPE_ERROR,
    APIKEY_ADD_ENDPOINT_URL,
    APIKEY_GET_ENDPOINT_URL,
    APIKEY_DELETE_ENDPOINT_URL,
    APIKEY_LIST_ENDPOINT_URL,
    APIKEY_EDIT_ENDPOINT_URL,
    COLLECTION_LIST_ENDPOINT_URL,
    COLLECTION_CREATE_ENDPOINT_URL,
    COLLECTION_EDIT_ENDPOINT_URL,
    COLLECTION_DELETE_ENDPOINT_URL,
    IMAGE_GET_ENDPOINT_URL,
    IMAGE_GET_PAGED_ENDPOINT_URL,
    IMAGE_GET_ALL_ENDPOINT_URL,
    IMAGE_EDIT_ENDPOINT_URL,
    IMAGE_DELETE_ENDPOINT_URL,
    UPLOAD_ENDPOINT_URL,
    TOTAL_RESOURCE_USAGE_METRICS_ENDPOINT,
    DAILY_RESOURCE_USAGE_METRICS_ENDPOINT,
    GET_API_KEY_LOGS_ENDPOINT
};