// HTTP STATUS CODES
const HTTP_STATUS_OK = 200;
const HTTP_STATUS_UNAUTHORIZED = 401;

// ENDPOINTS


// USER
const GET_USER_ENDPOINT_URL  = "/user/get";
const EDIT_USER_ENDPOINT_URL = "/user/edit"
//AUTH 
const LOGIN_ENDPOINT_URL  = "/auth/login";
const REGISTER_ENDPOINT_URL  = "/auth/register";
const PING_AUTH_ENDPOINT_URL  = "/auth/pingauth";


// NOTIFICATIONS TYPES
const NOTIFICATION_TYPE_SUCCESS = "success"
const NOTIFICATION_TYPE_ERROR = "error"

export
{
HTTP_STATUS_OK,
HTTP_STATUS_UNAUTHORIZED,
GET_USER_ENDPOINT_URL,
LOGIN_ENDPOINT_URL,
EDIT_USER_ENDPOINT_URL,
REGISTER_ENDPOINT_URL,
PING_AUTH_ENDPOINT_URL,
NOTIFICATION_TYPE_SUCCESS,
NOTIFICATION_TYPE_ERROR,
}