version: '3.4'

services:
  
  envoygateway:
    build: Envoy/
    ports:
      - "9902:9902"
      - "10000:10000"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml

  imagevault.authenticationservice:
    image: ${DOCKER_REGISTRY-}imagevaultauthenticationservice
    build:
      context: .
      dockerfile: ImageVault.AuthenticationService/Dockerfile
    ports:
      - "2100:2100"
      - "2101:2101"  
    volumes:
      - ./certs:/https 
      
  imagevault.userservice:
    image: ${DOCKER_REGISTRY-}imagevaultuserservice
    build:
      context: .
      dockerfile: ImageVault.UserService/Dockerfile
    ports:
      - "2103:2103"
      - "2104:2104"  
    volumes:
      - ./certs:/https

  rabbitmq : 
   build : RabbitMq/
   ports : 
     - "5672:5672"
     - "15672:15672"
   volumes:
     - rabbitMq:/var/lib/rabbitmq

  imagevault.requestmetricsservice:
    image: ${DOCKER_REGISTRY-}imagevaultrequestmetricsservice
    build:
      context: .
      dockerfile: ImageVault.RequestMetricsService/Dockerfile
    ports:
      - "2105:2105"
      - "2106:2106"  
    volumes:
      - ./certs:/https

  sqlserver : 
   build : MsSqlServer/
   ports : 
    - "1433:1433"
   environment : 
    ACCEPT_EULA : "Y"
    MSSQL_SA_PASSWORD : "TestPassword1!"
   volumes :
    - msSqlServer:/var/opt/mssql

volumes:
  rabbitMq:
    external: true
  msSqlServer:
    external: true
