version: '3.4'

services:
  
  envoygateway:
    build: Envoy/
    ports:
      - "9902:9902"
      - "10000:10000"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml

  imagevault.authenticationservice:
    image: ${DOCKER_REGISTRY-}imagevaultauthenticationservice
    build:
      context: .
      dockerfile: ImageVault.AuthenticationService/Dockerfile
    ports:
      - "8083:8083"
      - "8084:8084"  
    volumes:
      - ./certs:/https 
      
  imagevault.userservice:
    image: ${DOCKER_REGISTRY-}imagevaultuserservice
    build:
      context: .
      dockerfile: ImageVault.UserService/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"  
    volumes:
      - ./certs:/https  
