import { Chance } from "chance";

const chance = new Chance();


const log = [ 
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image Removed, Image id  ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image Removed, Image id  ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image Removed, Image id  ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image Removed, Image id  ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image Removed, Image id  ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image Removed, Image id  ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image Removed, Image id  ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image Removed, Image id  ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image Removed, Image id  ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image Removed, Image id  ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},{Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image Removed, Image id  ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image Removed, Image id  ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image Removed, Image id  ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image Removed, Image id  ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image Removed, Image id  ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image requested , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
    {Date:chance.date({string: true}),Message:`Image uploaded , Image id ${chance.hash()}`},
]

function shuffleArray(array)
{
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));

        [array[i], array[j]] = [array[j], array[i]];
      }
      return array;
}
export function getLogPage(pageNumber,chunkSize)
{   
    if(pageNumber < 1 || chunkSize < 1) return;

    const logs = shuffleArray(log)

    const startIndex = (pageNumber - 1) * chunkSize;
    const endIndex = startIndex + chunkSize;
    return logs.slice(startIndex, endIndex);
}
